### ISSUE TITLE
App getting Crashed with android.content.res.Resources$NotFoundException: Resource ID

### ISSUE THREAD

**Issue by BlueYeti1881** [arawind/kmap-android#1]
My app crashed with following error,

'android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.Resources.getValue(Resources.java:1123)
        at android.content.res.Resources.getColor(Resources.java:805)
        at android.support.v7.widget.ResourcesWrapper.getColor(ResourcesWrapper.java:157)
        at com.nepalpolice.kmap.AutoResizeTextView.setBG(AutoResizeTextView.java:338)
        at com.nepalpolice.kmap.AutoResizeTextView.addColor(AutoResizeTextView.java:362)
        at com.nepalpolice.kmap.Launcher.gridOnItemClick(Launcher.java:207)
        at com.nepalpolice.kmap.Launcher.access$100(Launcher.java:29)
        at com.nepalpolice.kmap.Launcher$2.onItemClick(Launcher.java:174)
        at android.widget.AdapterView.performItemClick(AdapterView.java:299)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:2904)
        at android.widget.AbsListView$3.run(AbsListView.java:3643)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)'

Please help

**Comment by arawind** [comment]
Hi there! Thanks for trying it out, but this project was a very hacky attempt at learning android, but nothing came out of it. The app doesn't do anything, sorry for the false hopes!
